- Core AI:
    - Ollama:
        icon: si-ollama
        href: http://192.168.1.11:11434
        server: my-docker-host
        container: ollama_jetson

- Management:
    - Web Monitor:
        icon: mdi-monitor-dashboard
        href: http://192.168.1.11:8050
        server: my-docker-host
        container: home_ai_dashboard
    - Netdata:
        icon: mdi-chart-line
        href: http://192.168.1.11:19999
        server: my-docker-host
        container: netdata

- Remote:
    - Main PC:
        icon: mdi-microsoft-windows
        href: http://192.168.1.16:5000
        description: Brain-Crunching AI Host (Web Monitor)
