- search:
    provider: google
    focus: true

- resources:
    cpu: true
    memory: true

- netdata:
    url: http://192.168.1.11:19999
    charts:
      - system.cpu
      - mem.available
      - sensors.thermal_thermal_zone0_temp # Often maps to CPU/GPU SoC on Jetson
